theme: jekyll-theme-minimal
title: NICE Research Group
description: Homepage for the NICE Research Group, University of Minnesota, 
directed by Dr. Moin Syed
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: People
    url: people
  - title: Projects
    url: projects
  - title: Publications
    url: publications
  - title: Resources
    url: resources
  - title: Blog
    url: blog
  - title: Talks
    url: talks
  - title: Prospective Students
    url: students